# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 00:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CloudNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=50)),
                ('config', models.TextField()),
                ('type', models.TextField()),
            ],
            options={
                'db_table': 'cloudnode',
            },
        ),
        migrations.CreateModel(
            name='CloudRing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'cloudring',
            },
        ),
        migrations.CreateModel(
            name='ObjectData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.FileField(upload_to=b'')),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'objectdata',
            },
        ),
        migrations.AddField(
            model_name='cloudnode',
            name='ring',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.CloudRing'),
        ),
    ]
