# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 03:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CloudNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config', models.TextField()),
                ('type', models.CharField(max_length=50)),
                ('ip_address', models.GenericIPAddressField(default=None)),
                ('identifier', models.CharField(max_length=255, null=True, verbose_name='identifier')),
                ('status', models.IntegerField(blank=True, choices=[(1, 'FULL'), (2, 'OK'), (3, 'CORRUPTED')], default=2, null=True)),
            ],
            options={
                'db_table': 'cloudnode',
            },
        ),
        migrations.CreateModel(
            name='CloudRing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'cloudring',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('identifier', models.CharField(max_length=255, null=True, verbose_name='identifier')),
                ('status', models.IntegerField(blank=True, choices=[(1, 'UPDATE'), (2, 'NOT_UPDATE'), (3, 'AVAILABLE'), (4, 'NOT_AVAILABLE')], default=3, null=True)),
                ('last_modified', models.DateTimeField(auto_now_add=True, verbose_name='last_modified')),
                ('path', models.CharField(max_length=255, null=True, verbose_name='path')),
                ('content', models.FileField(null=True, upload_to=b'', verbose_name='content')),
                ('is_folder', models.BooleanField(default=True, verbose_name='is_folder')),
                ('is_root', models.BooleanField(default=False, verbose_name='is_root')),
                ('size', models.IntegerField(editable=False, null=True, verbose_name='size')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='dashboard.File', verbose_name='parent')),
            ],
            options={
                'db_table': 'file',
            },
        ),
        migrations.CreateModel(
            name='FileReplica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=255, null=True, verbose_name='identifier')),
                ('status', models.IntegerField(blank=True, choices=[(1, 'UPDATE'), (2, 'NOT_UPDATE')], default=2, null=True)),
            ],
            options={
                'db_table': 'replica',
            },
        ),
        migrations.AddField(
            model_name='cloudnode',
            name='ring',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.CloudRing'),
        ),
    ]
