# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='data',
            field=models.FileField(default=0, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='file',
            name='parent_path',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='file',
            name='path',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='file',
            name='size',
            field=models.IntegerField(default=0),
        ),
    ]
