# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20170323_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='path',
            field=models.CharField(max_length=255, null=True, verbose_name='path'),
        ),
    ]
