# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 14:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_file_path'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ObjectData',
        ),
    ]
