# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 08:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_delete_objectdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileReplica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=255, null=True, verbose_name='identifier')),
                ('status', models.IntegerField(blank=True, choices=[(1, 'UPDATE'), (2, 'NOT_UPDATE')], default=2, null=True)),
            ],
            options={
                'db_table': 'replica',
            },
        ),
        migrations.RemoveField(
            model_name='cloudring',
            name='identifier',
        ),
        migrations.AddField(
            model_name='cloudnode',
            name='ip_address',
            field=models.GenericIPAddressField(default=None),
        ),
        migrations.AddField(
            model_name='cloudnode',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'FULL'), (2, 'OK'), (3, 'CORRUPTED')], default=2, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='identifier',
            field=models.CharField(max_length=255, null=True, verbose_name='identifier'),
        ),
        migrations.AddField(
            model_name='file',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'UPDATE'), (2, 'NOT_UPDATE'), (3, 'AVAILABLE'), (4, 'NOT_AVAILABLE')], default=3, null=True),
        ),
        migrations.AlterField(
            model_name='cloudnode',
            name='identifier',
            field=models.CharField(max_length=255, null=True, verbose_name='identifier'),
        ),
        migrations.AlterField(
            model_name='cloudnode',
            name='type',
            field=models.CharField(max_length=50),
        ),
    ]
